from pathlib import Path

p = Path('playlocal_server.py')
s = p.read_text()

s = s.replace("SITE_TOKENS = {}\nSITE_TOKEN_TTL = 12 * 60 * 60\n", "SITE_TOKENS = {}\nSITE_TOKEN_TTL = 12 * 60 * 60\nBROWSER_BRIDGES = {}\n")

old = """    payload = {\n        'exp': int(time.time()) + 10 * 60,\n        'nonce': secrets.token_urlsafe(18),\n        'accountId': account_id,\n        'slot': safe_slot,\n        'reservationUrl': booking_url,\n    }\n"""
new = """    bridge_id = secrets.token_urlsafe(24)\n    bridge_exp = time.time() + 10 * 60\n    with LOCK:\n        expired = [k for k, v in BROWSER_BRIDGES.items() if v.get('exp', 0) <= time.time()]\n        for k in expired:\n            BROWSER_BRIDGES.pop(k, None)\n        BROWSER_BRIDGES[bridge_id] = {\n            'accountId': account_id,\n            'sessionToken': session_token,\n            'exp': bridge_exp,\n        }\n    payload = {\n        'exp': int(bridge_exp),\n        'nonce': secrets.token_urlsafe(18),\n        'bridgeId': bridge_id,\n        'accountId': account_id,\n        'slot': safe_slot,\n        'reservationUrl': booking_url,\n    }\n"""
if old not in s:
    raise SystemExit('ticket payload marker not found')
s = s.replace(old, new, 1)

marker = """def browser_credentials(account_id):\n    account = configured_server_accounts().get(str(account_id or ''))\n    if not account:\n        raise ApiError('ACCOUNT_NOT_FOUND', 'That server account is not configured.', 404, True)\n    return {'username': account['username'], 'password': account['password']}\n\n\n"""
insert = marker + """def browser_session_material(bridge_id, account_id):\n    bridge_id = str(bridge_id or '')\n    account_id = str(account_id or '')\n    now = time.time()\n    with LOCK:\n        item = BROWSER_BRIDGES.pop(bridge_id, None)\n    if not item or item.get('exp', 0) <= now or item.get('accountId') != account_id:\n        raise ApiError('BROWSER_SESSION', 'The temporary PlayLocal browser session expired. Please retry verification.', 401, True)\n    sess = get_session(item.get('sessionToken', ''), account_id)\n    cookies = []\n    cookie_store = getattr(sess, 'cookies', None)\n    jar = getattr(cookie_store, 'jar', None)\n    if jar is not None:\n        try:\n            for c in jar:\n                name = str(getattr(c, 'name', '') or '')\n                value = str(getattr(c, 'value', '') or '')\n                if not name:\n                    continue\n                domain = str(getattr(c, 'domain', '') or '.playlocal.com')\n                path = str(getattr(c, 'path', '') or '/')\n                cookies.append({\n                    'name': name, 'value': value, 'domain': domain, 'path': path,\n                    'secure': bool(getattr(c, 'secure', False)),\n                })\n        except TypeError:\n            pass\n    if not cookies and cookie_store is not None:\n        try:\n            values = cookie_store.get_dict() if hasattr(cookie_store, 'get_dict') else dict(cookie_store)\n            for name, value in values.items():\n                cookies.append({\n                    'name': str(name), 'value': str(value),\n                    'domain': '.playlocal.com', 'path': '/', 'secure': True,\n                })\n        except Exception:\n            pass\n    if not cookies:\n        raise ApiError('BROWSER_SESSION', 'CourtFlow could not transfer the authenticated PlayLocal session.', 502, True)\n    return {'cookies': cookies, 'userAgent': UA}\n\n\n"""
s = s.replace(marker, insert, 1)

old_endpoint = """    def do_POST(self):\n        if self.path == '/browser-credentials':\n"""
new_endpoint = """    def do_POST(self):\n        if self.path == '/browser-session':\n            try:\n                expected = os.environ.get('COURTFLOW_BROWSER_SECRET', '')\n                supplied = self.headers.get('Authorization', '')\n                if supplied.lower().startswith('bearer '):\n                    supplied = supplied[7:]\n                if not expected or not secrets.compare_digest(str(supplied), str(expected)):\n                    payload = {'ok': False, 'message': 'Unauthorized.'}\n                    status = 401\n                else:\n                    n = int(self.headers.get('Content-Length', '0'))\n                    req = json.loads(self.rfile.read(n) or b'{}')\n                    material = browser_session_material(req.get('bridgeId'), req.get('accountId'))\n                    payload = {'ok': True, **material}\n                    status = 200\n            except ApiError as e:\n                payload = {'ok': False, 'message': e.message}\n                status = e.status\n            except Exception:\n                payload = {'ok': False, 'message': 'Browser session transfer error.'}\n                status = 500\n            raw = json.dumps(payload).encode()\n            self.send_response(status)\n            self.send_header('Content-Type', 'application/json')\n            self.send_header('Cache-Control', 'no-store')\n            self.send_header('Content-Length', str(len(raw)))\n            self.end_headers()\n            self.wfile.write(raw)\n            return\n        if self.path == '/browser-credentials':\n"""
if old_endpoint not in s:
    raise SystemExit('do_POST marker not found')
s = s.replace(old_endpoint, new_endpoint, 1)
p.write_text(s)

bp = Path('browser_service/server.js')
b = bp.read_text()

old_fetch = """async function fetchCredentials(accountId) {\n  const r = await fetch(MAIN_API + '/browser-credentials', {\n    method: 'POST',\n    headers: {\n      'content-type': 'application/json',\n      'authorization': 'Bearer ' + SHARED_SECRET,\n    },\n    body: JSON.stringify({ accountId }),\n  });\n  const b = await r.json().catch(() => null);\n  if (!r.ok || !b?.ok || !b?.username || !b?.password) {\n    throw new Error(b?.message || 'Could not retrieve the assigned PlayLocal account from CourtFlow.');\n  }\n  return b;\n}\n\nasync function loginToPlayLocal(page, username, password) {\n  await page.goto('https://www.playlocal.com/sign_in', { waitUntil: 'domcontentloaded', timeout: 30000 });\n  await page.waitForSelector('input[type=\"password\"]', { timeout: 15000 });\n  const found = await page.evaluate(({ username, password }) => {\n    const email = document.querySelector('input[type=\"email\"], input[name*=\"email\" i], input[name*=\"user\" i]');\n    const pass = document.querySelector('input[type=\"password\"]');\n    if (!email || !pass) return false;\n    const set = (el, value) => {\n      el.focus();\n      el.value = value;\n      el.dispatchEvent(new Event('input', { bubbles: true }));\n      el.dispatchEvent(new Event('change', { bubbles: true }));\n    };\n    set(email, username);\n    set(pass, password);\n    const form = pass.form || email.form || document.querySelector('form');\n    if (!form) return false;\n    if (form.requestSubmit) form.requestSubmit(); else form.submit();\n    return true;\n  }, { username, password });\n  if (!found) throw new Error('PlayLocal sign-in fields were not recognized.');\n  await page.waitForNavigation({ waitUntil: 'domcontentloaded', timeout: 20000 }).catch(() => null);\n  if (new URL(page.url()).pathname === '/sign_in') {\n    const stillHasPassword = await page.$('input[type=\"password\"]');\n    if (stillHasPassword) throw new Error('PlayLocal rejected the assigned account or returned to sign-in.');\n  }\n}\n\n"""
new_fetch = """async function fetchSessionMaterial(bridgeId, accountId) {\n  const r = await fetch(MAIN_API + '/browser-session', {\n    method: 'POST',\n    headers: {\n      'content-type': 'application/json',\n      'authorization': 'Bearer ' + SHARED_SECRET,\n    },\n    body: JSON.stringify({ bridgeId, accountId }),\n  });\n  const data = await r.json().catch(() => null);\n  if (!r.ok || !data?.ok || !Array.isArray(data.cookies) || !data.cookies.length) {\n    throw new Error(data?.message || 'Could not transfer the authenticated PlayLocal session.');\n  }\n  return data;\n}\n\nasync function applySessionMaterial(page, material) {\n  await page.setUserAgent(material.userAgent || 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36');\n  await page.setExtraHTTPHeaders({ 'Accept-Language': 'en-US,en;q=0.9' });\n  const cookies = (material.cookies || []).map(c => ({\n    name: String(c.name || ''),\n    value: String(c.value || ''),\n    domain: String(c.domain || '.playlocal.com'),\n    path: String(c.path || '/'),\n    secure: !!c.secure,\n  })).filter(c => c.name);\n  if (!cookies.length) throw new Error('Authenticated PlayLocal session contained no cookies.');\n  await page.setCookie(...cookies);\n}\n\n"""
if old_fetch not in b:
    raise SystemExit('browser login block not found')
b = b.replace(old_fetch, new_fetch, 1)

old_start = """    const payload = verifyTicket(req.body?.ticket);\n    const credentials = await fetchCredentials(payload.accountId);\n    browser = await launchBrowser();\n    const page = await browser.newPage();\n    await page.setViewport(VIEWPORT);\n    await page.setJavaScriptEnabled(true);\n    await loginToPlayLocal(page, credentials.username, credentials.password);\n    await prepareReservation(page, payload);\n"""
new_start = """    const payload = verifyTicket(req.body?.ticket);\n    if (!payload.bridgeId) throw new Error('Browser ticket is missing its authenticated session bridge.');\n    const material = await fetchSessionMaterial(payload.bridgeId, payload.accountId);\n    browser = await launchBrowser();\n    const page = await browser.newPage();\n    await page.setViewport(VIEWPORT);\n    await page.setJavaScriptEnabled(true);\n    await applySessionMaterial(page, material);\n    await prepareReservation(page, payload);\n    if (new URL(page.url()).pathname === '/sign_in') {\n      throw new Error('PlayLocal did not accept the transferred authenticated session. Please retry.');\n    }\n"""
if old_start not in b:
    raise SystemExit('browser session start block not found')
b = b.replace(old_start, new_start, 1)
bp.write_text(b)
